backend:
  name: github
  repo: yourbrother88/micbible
  branch: main
  auth_type: implicit
  app_id: Ov23liO1qhNgwlCNOFWA

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }